### ISSUE TITLE
Issue with prompt syntax from "Prompt Fusion" Extension

### ISSUE THREAD

**Issue by Arthur-McArthur** [Physton/sd-webui-prompt-all-in-one#7]
Very useful extension! Thank you!

I am finding issues when using the prompt syntax for "Prompt Fusion" extension. https://github.com/ljleb/prompt-fusion-extension

For example: [night light:magical forest: 5, 15]

This gets broken into two pieces: " [night light:magical forest: 5," and " 15]".

**Comment by Physton** [comment]
Thank you for your support!
Is the syntax structure always enclosed by [] on both sides? If so, I can exclude the text enclosed by [] from being subjected to word segmentation processing.

**Comment by Arthur-McArthur** [comment]
Thank you for the quick reply! 
Yes, the default syntax structure is enclosed by []. There is an option for custom syntax to change it but I think most people use the default one.

**Comment by Physton** [comment]
It has been fixed. Please try again.

**Comment by Arthur-McArthur** [comment]
Still having issues with this one: For example if I type: 
"[tree:bird: 10, 20],"
It gets shortened to "[tree:bird:10, 20]," in the Default Input Box, but in your extension it shows:
"[tree:bird:10" and then "20]" 
and it does not interpolate between them

**Comment by Physton** [comment]
There is a comma at the end of the text, and there is no particularly good solution to it.

**Comment by Arthur-McArthur** [comment]
Hmm, the problem might be that it is removing the space between "dogs:" and "10". Is it possible to try keeping the whitespace in there?

**Comment by Physton** [comment]
I tried to input "[tree:dogs:10, 20]" and the expansion did not remove the spaces in the text, it was displayed completely. You need to remove the comma at the end.

**Comment by Arthur-McArthur** [comment]
Here is a gif showing my issue: https://i.imgur.com/9rqXC5T.gif
Is it possible to maybe ignore the whitespace shortening within the []?

**Comment by Physton** [comment]
I saw your screenshot.

If you mean that it was divided into two tags, it's because you need to enter it in the expansion input box, not the one provided by the webui.

If the text "[tree:dogs: 10, 20]" has been changed to "[tree:dogs:10, 20]" and lost a space, there is currently no better way to handle it.

**Comment by Arthur-McArthur** [comment]
Ok that makes sense! Thanks for explaining it to me.

The only issue I have now is that left-clicking to edit on "[tree:dogs:10, 20]" splits it into two.

**Comment by Physton** [comment]
OK, it's already half past two in the morning in China and I need to go to bed. After I wake up, I will fix it.

**Comment by Arthur-McArthur** [comment]
Great, thank you for the lightning quick fixes! Have a good night

**Comment by Physton** [comment]
Hi, all the questions you asked have been fixed and now you can directly enter text like "[night light:magical forest: 5, 15]" in the input box of webui

**Comment by Physton** [comment]
- [night light:magical forest: 5, 15]
- [night light:magical forest:norvegian territory: 5, 15, 25:catmull]
- (fire extinguisher: 1.0, 2.0)
- [(fire extinguisher: 1.0, 2.0)::5]
- [lion:bird:girl: , 7, 10]

I have tested all the above text and they can be used normally. If there are other formats, please send them to me for testing. thank u

**Comment by Arthur-McArthur** [comment]
Working perfectly, thank you so much!
